version: '3'
services:
  apache-php:
    image: php:apache
    container_name: php_apache
    ports:
      - "80:80"
    volumes:
      - ./php:/var/www/html
    command: sh -c "docker-php-ext-install mysqli && apache2-foreground"
    networks:
      - php_python_network

  python-flask:
    image: python:3.11.5
    container_name: python_flask
    volumes:
      - ./python:/app
    command: sh -c "pip install flask tensorflow==2.14.0 numpy==1.24.3 && python /app/app.py"
    ports:
      - "5000:5000"
    networks:
      - php_python_network

  mysql-db:
    image: mysql:latest
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: your_database_name
      MYSQL_USER: your_database_user
      MYSQL_PASSWORD: your_database_password
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      - php_python_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: my-phpmyadmin
    environment:
      PMA_HOST: mysql-db
      PMA_USER: your_database_user
      PMA_PASSWORD: your_database_password
    ports:
      - "8080:80"
    networks:
      - php_python_network

networks:
  php_python_network:
    driver: bridge