default:
  image:
  services:

stages:
  - data_preparation
  - training
  - evaluation
  - deployment

workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'

# Data Preparation
data_preparation:
  stage: data_preparation
  cache:
    key: ${CI_COMMIT_REF_SLUG}-data_preparation
  script:
    - py3 python/scripts/data_preparation.py
  artifacts:
    expire_in: 1 month
    paths:
      - python/csv/output
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'

# Training
training:
  stage: training
  cache:
    key: ${CI_COMMIT_REF_SLUG}-training
  script:
    - py3 python/scripts/build_model.py
  artifacts:
    expire_in: 1 month
    paths:
      - python/models
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'


# Evaluation
evaluation:
  stage: evaluation
  script:
    - py3 python/scripts/test_model.py
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'

# Deployment
deployment:
  stage: deployment
  script:
    - ls
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'